### ISSUE TITLE
Checkbox prompt text overlaps on Windows

### ISSUE THREAD

**Issue by teaphi** [tmbo/questionary#92] opened 2020-12-05 23:44 UTC
Text overlap
```python
import questionary
choices = []
for i in range(0,101):
    choices.append(str(i))
questionary.checkbox("Checkbox!", choices)
```
![GIF 2020-12-6 7-43-32.gif](https://i.loli.net/2020/12/06/1nW8aAsRg45hqcr.gif)

**Comment by kiancross** [comment] 2020-12-06 15:28
Cannot reproduce this on Linux - potentially a bug isolated to Windows.

**Comment by kiancross** [comment] 2020-12-06 15:29
@teaphi Which version of prompt_toolkit are you using?

**Comment by HelloGwkki** [comment] 2020-12-06 22:10
@kiancross 3.0.8

**Comment by YashDjsonDookun** [comment] 2021-08-23 15:10
I assume this has been fixed since I can't seem to replicate this issue on my windows machines.
I believe this can be closed. 👍

**Comment by kiancross** [comment] 2021-08-23 16:36
@YashDjsonDookun Which version of prompt toolkit are you using? I will double check on Windows tonight too.

**Comment by beliaev-maksim** [comment] 2022-04-10 17:41
@tmbo 
cannot be reprdocued on latest master

**Comment by tmbo** [comment] 2022-04-10 18:06
Sounds great, let’s close this then 🎉

**Closed by tmbo** 2022-04-10 18:06 UTC
Labels: Bug
