### ISSUE TITLE
questionary Printing Incorrect Colors to Terminal

### ISSUE THREAD

**Issue by Wulf-Steppen** [tmbo/questionary#256] opened 2022-09-29 06:21 UTC
### Describe the bug

I'm working on a cl app and am using questionary in tandem with rich. I noticed while building a help page for available color options that passing a hex value to questionary will result, sometimes, in the in correct color being returned.

```
flat_ = Style(

    [
        ("qmark", "fg:#673ab7 bold"),
        ("pointer", "fg:#673ab7 bold"),
        ("selected", f"fg:{theme} bold"),
        ("answer", f"fg:{theme}"),
    ]
)
```

Where {theme} is the hex value. Here is an example of the color help page using rich to render the hex and an example of the same hex value being passed to questionary:

![rich colors](https://user-images.githubusercontent.com/11824463/192953412-f0d97852-53bc-4077-bc61-d766a5343304.png)

![rich v question](https://user-images.githubusercontent.com/11824463/192953517-c182c28e-7572-4f93-a2f1-3fa99f4e12b4.png)

### Example

```python
import questionary
from rich import print

hex = some_hex

questionary.confirm("is this your hex? {hex}", qmark=">>", default=True, style=flat_).ask()
print("[{hex}]This is the same hex value and color using rich: {hex}[/{hex}]")
```

### Steps to reproduce

Pass a hex value to both questionary and print and observe different color outputs

### Expected behaviour

I'm inclined to believe rich is rendering the colors correctly as they match hex values I can find in other places.

### Latest version

- [X] I have checked that this issue occurs on the latest version of questionary.

### Questionary version

1.10.0

### Prompt Toolkit version

3.0.31

### Operating System

Windows

**Comment by kiancross** [comment] 2022-11-29 01:41
I wonder if the bug is in the mapping between colour names and hex codes in your code? Can you provide a self-contained [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

 The following example worked for me:

```python3
import questionary

theme_col = "#afff5f"

theme = questionary.Style(
    [
        ("qmark", "fg:#673ab7 bold"),
        ("pointer", "fg:#673ab7 bold"),
        ("selected", f"fg:{theme_col} bold"),
        ("answer", f"fg:{theme_col}"),
    ]
)

questionary.confirm(
    f"is this your hex? {theme_col}", qmark=">>", default=True, style=theme
).ask()
```

![Result](https://user-images.githubusercontent.com/11011464/204417366-9129167d-77c7-44a5-bcaa-5dcabcd2b40c.png)

**Comment by kiancross** [comment] 2023-05-22 09:23
Closing this as I can't reproduce it, but feel free to reply with any updated info, and I can re-open it.

**Closed by kiancross** 2023-05-22 09:23 UTC
Labels: Bug
