### ISSUE TITLE
Pre-selected value in list

### ISSUE THREAD

**Issue by lazee** [tmbo/questionary#57] opened 2020-09-14 17:27 UTC
Hi. I'm sorry if this has already been answered before...And thank you for questionary btw. 

Is it possible in a select to have a preselected option? I have found the default-settings but it doesn't behave the way I would expect.

![image](https://user-images.githubusercontent.com/11016/93118049-f7838700-f6bf-11ea-8e94-da77f89423a4.png)
Here `review` is the default, but the marker stays on `test`. And if the user hits enter he will select `test` and not `review`.

In my scenario I will cache the last environment the user worked on and let him hit enter next time, instead of having to select from the list each time.

**Comment by kiancross** [comment] 2020-09-15 00:41
I think this is a duplicate of #43? If so, I have implemented the behaviour in #56, and it is awaiting review.

The `default` parameter is actually something slightly different, it defines the value that is returned if no value is selected. However, this doesn't really make sense for a `select` input (it makes more sense for the `checkbox`, where a value is not required to continue).

@tmbo Is there a reason the `select` input accepts a `default` parameter? Should `ctrl + c` return the `default` value instead of `none`?

**Comment by lazee** [comment] 2020-09-15 16:56
Thank you @kiancross . Indeed it is a copy. I just didn't find it. Thanks for your answer.

**Comment by tmbo** [comment] 2020-09-21 11:21
Right, yes I think we should point at the default value :+1: I don't think we should return a default value on keyboard interrupt, as it signals the user wants to abort / go back. 

I think there are two ways to define the selected value (either specifying a value for `default` or by marking the choice as selected in the array of choices), I think we should make sure that
- there isn't more than one choice selected
- we point to the selected value if there is one (otherwise this is odd, since we return the pointed at value and not the selected one...).

**Comment by kiancross** [comment] 2020-09-21 20:59
@tmbo In #56 I implemented the 'point at' behaviour by adding an `initial_value` field. Do you want to replace this with the `default` field, or remove the `default` field for `select` (obviously the `default` parameter does make sense for `checkbox` and it should remain for this type).

**Comment by tmbo** [comment] 2020-09-22 07:40
I think a default value makes the most sense for the select element (and would coincide with the pointed at element in this case). So I guess the least effort would be to adapt your or, use the logic to set the pointed at element but remove the parameter and only use `default`.

**Comment by kiancross** [comment] 2020-09-22 20:32
@tmbo Do you think it might be confusing that the same functionality is implemented using two differently named arguments (`default` and `initial_choice`) for `checkbox` and `select`? I think it would be nicer if they shared the same argument name, for consistency?

**Comment by tmbo** [comment] 2020-09-25 18:23
well, I would say that the behaviour from a users perspective should be consistent for arguments that share the same name. so if we implement it in the way that,
- `default` sets the default return value of the prompt AND also points to the set item
- and `initial_choice` allows the user to overwrite the above
this seems pretty consistent. WDYT?

**Comment by kiancross** [comment] 2020-09-25 23:18
@tmbo I think ideally:

- we would remove `default` from the `select` type (seeing as it doesn't make sense);
- rename `initial_choice` to `selected` (I think this is a better name in hindsight).

However, this may break backwards compatibility for those already using the `default` parameter on `select` (probably not many people though, seeing as it doesn't really do anything at the moment).

**Comment by Yajo** [comment] 2020-09-26 03:01
Breaking backwards compatibility for something broken doesn't seem like a big issue for me... this is more a fix than a new feature. I agree with @tmbo.

**Comment by tmbo** [comment] 2020-10-01 19:59
I think there is no right or wrong here, both approaches would work. I'd go for the `default` argument, as it doesn't break compatibility (I'd also consider the default element not being selected a bug, I don't think there is any use case where this would be the expected behaviour).

**Closed** 2020-10-04 14:33 UTC
Labels: Duplicate

**Comment by lazee** [comment] 2020-10-05 20:06
Thank you guys!

**Comment by WilliamStam** [comment] 2021-02-19 09:46
how dos this get used? i think im doing something wrong in my app :(

````
menu_list = list()
menu_list.append(questionary.Choice(
     title = f"test1 title",
     value = "test1"
))
menu_list.append(questionary.Choice(
     title = f"test2 title",
     value = "test2"
))

# print([x.value for x in menu_list])
# ['test2', 'test2']

action = questionary.select(
    "SELECT IT",
    choices=menu_list,
    default="test2"
).ask()

````

throws an error

````
ValueError: Invalid `default` value passed. The value (`test2`) does not exist in the set of choices. Please make sure the default value is one of the available choices.
````

**Comment by kiancross** [comment] 2021-02-19 12:29
@WilliamStam Haven't tested your particular example, but the line that says `default="test2"` should be `default=menu_list[1]` I think :)

**Comment by WilliamStam** [comment] 2021-02-20 10:42
that does actually work, thank you! seems slightly counter intuitive tho in a way lol
